server:
  port: 9094

eureka:
  client:
    service-url:
      defaultZone: ${eureka_url}

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: ${db_url}
    username: ${db_username}
    password: ${db_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    root: INFO
    com.shikbetumio.user: DEBUG
    org.springframework.web: ERROR
